esphome:
  name: esp32c6-occupancy
  friendly_name: ESP32C6-Occupancy

esp32:
  board: esp32-c6-devkitc-1
  partitions: partitions_zb.csv
  framework:
    type: esp-idf

external_components:
  - source: github://luar123/zigbee_esphome
    components: [zigbee]

binary_sensor:
  - platform: gpio
    pin: GPIO22
    name: "PIR Sensor"
    device_class: motion

zigbee:
  id: "zb"
  endpoints:
    - num: 1
      device_type: ON_OFF_OUTPUT
      clusters:
        - id: OCCUPANCY_SENSING
          attributes:
            - attribute_id: 0
              id: occu_sens
              type: bool
              report: true
              value: false

  on_join:
    then:
      - logger.log: "Joined network"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "x"

ota:
  - platform: esphome
    password: "x"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


captive_portal:
    